mysite/library/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('authors/<int:author_id>', views.author, name='author'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book'),
    path('search/', views.search, name='search'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('user_books/', views.UserBookListView.as_view(), name='user_books'),
    path('user_books/<int:pk>', views.UserBookDetailView.as_view(), name='user_book'),
    path('user_books/new', views.UserBookCreateView.as_view(), name='user_book_new'),
    path('user_books/<int:pk>/update', views.UserBookUpdateView.as_view(), name='user_book_update'),
    path('user_books/<int:pk>/delete', views.UserBookDeleteView.as_view(), name='user_book_delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('library/', include('library.urls')),
    path('admin/', admin.site.urls),
    # path('', RedirectView.as_view(url='library/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

mysite/library/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField
from PIL import Image
from django.utils.translation import gettext_lazy as _

class Genre(models.Model):
    name = models.CharField('Pavadinimas', max_length=200, help_text='Įveskite knygos žanrą (pvz. detektyvas)')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Žanras'
        verbose_name_plural = 'Žanrai'


class Book(models.Model):
    """Modelis reprezentuoja knygą (bet ne specifinę knygos kopiją)"""
    title = models.CharField(_('Title'), max_length=200)
    author = models.ForeignKey('Author', verbose_name=_("Author"), on_delete=models.SET_NULL, null=True, related_name='books')
    summary = models.TextField(_('Summary'), max_length=1000, help_text='Trumpas knygos aprašymas')
    description = HTMLField(_('Description'), null=True)
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Simbolių <a href="https://www.isbn-international.org/content/what-isbn">ISBN kodas</a>')
    genre = models.ManyToManyField(Genre, verbose_name=_("Genre"), help_text='Išrinkite žanrą(us) šiai knygai')
    cover = models.ImageField(_('Cover'), upload_to='covers', null=True)

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all())

    display_genre.short_description = 'Žanras'

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     """Nurodo konkretaus aprašymo galinį adresą"""
    #     return reverse('book-detail', args=[str(self.id)])

    class Meta:
        verbose_name = 'Knyga'
        verbose_name_plural = 'Knygos'


class BookInstance(models.Model):
    """Modelis, aprašantis konkrečios knygos kopijos būseną"""
    uuid = models.UUIDField(default=uuid.uuid4, help_text='Unikalus ID knygos kopijai')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    due_back = models.DateField('Bus prieinama', null=True, blank=True)
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('a', 'Administruojama'),
        ('p', 'Paimta'),
        ('g', 'Galima paimti'),
        ('r', 'Rezervuota'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
        help_text='Statusas',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField('Vardas', max_length=100)
    last_name = models.CharField('Pavardė', max_length=100)
    description = models.TextField('Aprašymas', max_length=2000, default='')

    class Meta:
        ordering = ['last_name', 'first_name']

    def display_books(self):
        return ', '.join(book.title for book in self.books.all())

    display_books.short_description = 'Knygos'

    # def get_absolute_url(self):
    #     """Returns the url to access a particular author instance."""
    #     return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name} {self.first_name}'


class BookReview(models.Model):
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, blank=True, related_name='reviews')
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Atsiliepimas', max_length=2000)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(default="default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profile"

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save(force_insert, force_update, using, update_fields)
        img = Image.open(self.photo.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.photo.path)

mysite/library/forms.py
from .models import BookReview, Profile, BookInstance
from django import forms
from django.contrib.auth.models import User

class BookReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview
        fields = ('content', 'book', 'reviewer',)
        widgets = {'book': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'last_name']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']


class DateInput(forms.DateInput):
    input_type = 'date'

class UserBookCreateForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['book', 'reader', 'due_back', 'status']
        widgets = {'reader': forms.HiddenInput(), 'due_back': DateInput()}

mysite/library/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

from django.shortcuts import render
from django.http import HttpResponse
from .models import Book, Author, BookInstance, Genre
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.views.generic.edit import FormMixin
from .forms import BookReviewForm, UserUpdateForm, ProfileUpdateForm, UserBookCreateForm
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext as _
from django.contrib.auth.mixins import UserPassesTestMixin

def index(request):
    # Suskaičiuokime keletą pagrindinių objektų
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Laisvos knygos (tos, kurios turi statusą 'g')
    num_instances_available = BookInstance.objects.filter(status__exact='g').count()

    # Kiek yra autorių
    num_authors = Author.objects.count()

    # Papildome kintamuoju num_visits, įkeliame jį į kontekstą.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    # perduodame informaciją į šabloną žodyno pavidale:
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        "num_visits": num_visits,
    }

    # renderiname index.html, su duomenimis kintamąjame context
    return render(request, 'index.html', context=context)


def authors(request):
    paginator = Paginator(Author.objects.all(), 2)
    page_number = request.GET.get('page')
    paged_authors = paginator.get_page(page_number)
    context = {
        'authors': paged_authors
    }
    return render(request, 'authors.html', context=context)


def author(request, author_id):
    single_author = get_object_or_404(Author, pk=author_id)
    return render(request, 'author.html', {'author': single_author})


class BookListView(generic.ListView):
    model = Book
    template_name = 'book_list.html'
    context_object_name = 'books'
    paginate_by = 2




class BookDetailView(FormMixin, generic.DetailView):
    model = Book
    template_name = 'book_detail.html'
    form_class = BookReviewForm

    def get_success_url(self):
        return reverse('book', kwargs={'pk': self.object.id})

    # standartinis post metodo perrašymas, naudojant FormMixin, galite kopijuoti tiesiai į savo projektą.
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.book = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(BookDetailView, self).form_valid(form)


def search(request):
    """
    paprasta paieška. query ima informaciją iš paieškos laukelio,
    search_results prafiltruoja pagal įvestą tekstą knygų pavadinimus ir aprašymus.
    Icontains nuo contains skiriasi tuo, kad icontains ignoruoja ar raidės
    didžiosios/mažosios.
    """
    query = request.GET.get('query')
    search_results = Book.objects.filter(Q(title__icontains=query) | Q(summary__icontains=query))
    return render(request, 'search.html', {'books': search_results, 'query': query})


@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, _('Username %s already exists!') % username)
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, _('Email %s already exists!') % email)
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    return redirect('login')
        else:
            messages.error(request, _('Passwords do not match!'))
            return redirect('register')
    return render(request, 'registration/register.html')

@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profile.html', context)

# cRud all
class UserBookListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'user_books.html'
    context_object_name = 'books'

    def get_queryset(self):
        return BookInstance.objects.filter(reader=self.request.user).filter(status__exact='p').order_by('due_back')

# cRud one
class UserBookDetailView(LoginRequiredMixin, generic.DetailView):
    model = BookInstance
    template_name = 'user_book.html'
    context_object_name = 'book'


# Crud
class UserBookCreateView(LoginRequiredMixin, generic.CreateView):
    model = BookInstance
    # fields = ['book', 'due_back', 'status']
    success_url = "/library/user_books/"
    template_name = 'user_book_form.html'
    form_class = UserBookCreateForm

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)

# crUd
class UserBookUpdateView(LoginRequiredMixin, generic.UpdateView, UserPassesTestMixin):
    model = BookInstance
    fields = ['book', 'due_back', 'status']
    success_url = "/library/user_books/"
    template_name = 'user_book_form.html'

    # def get_success_url(self):
    #     return reverse('user_book', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)

    def test_func(self):
        bookinstance = self.get_object()
        return self.request.user == bookinstance.reader


# cruD
class UserBookDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = BookInstance
    success_url = "/library/user_books/"
    template_name = 'user_book_delete.html'
    context_object_name = 'book'

    def test_func(self):
        bookinstance = self.get_object()
        return self.request.user == bookinstance.reader

mysite/library/templates/author.html
{% extends "base.html" %}

{% block title %}Author{% endblock %}

{% block content %}
    <div class="container author">
    <h4>{{ author.first_name }} {{ author.last_name }}</h4>
    <hr/>
    <p>{{ author.description }}</p>
    </hr>
    </br>
    <h5>Mes turime šias {{ author.first_name }} {{ author.last_name }} knygas:</h5>
    {% for book in author.books.all %}
       <li>{{ book.title }}</li>
    {% endfor %}
    </div>
{% endblock %}

mysite/library/templates/authors.html
{% extends "base.html" %}

{% block title %}Authors{% endblock %}

{% block content %}
  <h1>Autoriai</h1>
  <p>Mūsų knygų autorių sąrašas.</p>
  {% for author in authors %}
<li><a href="{% url 'author' author.id %}">{{author.first_name}} {{author.last_name}}</a></li>
    {% endfor %}

<div class="container puslapiai">
    <nav aria-label="...">
        {% if authors.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in authors.paginator.page_range %}
                    {% if authors.number == i %}
                        <li class="page-item active">
                            <a class="page-link">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

mysite/library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% load i18n %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
  <div class="container">
    <a class="navbar-brand" href="#">
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-book-half" viewBox="0 0 16 16">
  <path d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
</svg>
    Rajono biblioteka</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Pradžia</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authors' %}">Autoriai</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books' %}">Knygos</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">
          <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
          </svg>
        {{ user.get_username }}</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'user_book_new'%}">Nauja knyga</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'user_books'%}">Mano knygos</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}">Atsijungti</a></li>
      {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Prisijungti</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">Registruotis</a></li>
      {% endif %}


        <li>
            <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
            <input name="query" class="form-control" type="text" placeholder="Paieška">
            </form>
        </li>
      {% load i18n %}
      <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
<!--        <input name="next" type="hidden" value="{{ redirect_to }}"/>-->
        <select name="language" onchange="this.form.submit()">
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% for lang in LANGUAGES %}
          <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected" {% endif %}>
            {{ lang.1 }}
          </option>
          {% endfor %}
        </select>
      </form>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
{% block content %}{% endblock %}
</div>


  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>

mysite/library/templates/book_detail.html
{% extends "base.html" %}

{% block title %}Book Detail{% endblock %}

{% block content %}
 {% load static %}
<div class="col-md-4 d-flex align-items-stretch">
<div class="card mb-4 shadow-sm">
  {% if book.cover %}
    <img src="{{ book.cover.url }}" class="card-img-top" alt="...">
  {% else %}
    <img src="{% static 'img/no-image.png' %}" class="card-img-top">
  {% endif %}
</div>
</div>
  <h1>{{ book.title }}</h1>
  <p><strong>Autorius:</strong> <a href="{% url 'author' book.author.pk %}">{{ book.author }}</a></p>
  <p><strong>Aprašymas:</strong> {{ book.description | safe }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Žanras:</strong> {{ book.genre.all|join:", " }}</p>
  <div style="margin-left:20px;margin-top:20px">
    </br>
  <h4>Atsiliepimai:</h4>
  {% if user.is_authenticated %}
  <div class="fieldWrapper">
    <hr><br/>
    <h4>Palikite atsiliepimą:</h4>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.content }}</br>
      <input type="submit" value="Išsaugoti">
    </form>
  </div>
  {% endif %}
  {% if book.reviews.all %}
    {% for review in book.reviews.all %}
      <hr>
      <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
      <p>{{ review.content }}</p>
    {% endfor %}
  {% else %}
    <p>Knyga neturi atsiliepimų</p>
  {% endif %}
    <hr/>

    <h4>Kopijos:</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Bus grąžinta:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p class="text-muted"><strong>Id:</strong> {{ copy.uuid }} ({{ copy.reader }})</p>
    {% endfor %}
  </div>
{% endblock %}

mysite/library/templates/book_list.html
{% extends "base.html" %}

{% block title %}Books{% endblock %}

{% block content %}
 {% load static %}
    <h1>Knygų sąrašas</h1></br>
    {% if books %}
    <div class="row">
      {% for book in books %}
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="card mb-4 shadow-sm">
            {% if book.cover %}
              <img src="{{ book.cover.url }}" class="card-img-top" alt="...">
            {% else %}
              <img src="{% static 'img/no-image.png' %}" class="card-img-top">
            {% endif %}
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
              <p class="card-text"><a href="{{ book.id }}">{{ book.title }}</a></p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% else %}
      <p>Bibliotekoje knygų nėra.</p>
    {% endif %}

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

mysite/library/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Welcome" %}{% endblock %}

{% block content %}
  <h1>{% trans "Local library" %}</h1>
  <p>{% trans "Welcome to my Library" %}</p>
  <p>{% trans "Today we have:" %}</p>
  <ul>
    <li><strong>{% trans "Books" %}:</strong> {{ num_books }}</li>
    <li><strong>{% trans "Book Instances" %}:</strong> {{ num_instances }}</li>
    <li><strong>{% trans "Now Available" %}:</strong> {{ num_instances_available }}</li>
    <li><strong>{% trans "Authors" %}:</strong> {{ num_authors }}</li>
  </ul>

<p>{% blocktrans %}Your visits: {{ num_visits }} {% endblocktrans %}</p>
{% endblock %}


<!--  <h1>Rajono biblioteka</h1>-->
<!--  <p>Sveiki atvykę į knygų rojų!</p>-->
<!--  <p>Šiuo metu turime:</p>-->
<!--  <ul>-->
<!--    <li><strong>Knygų:</strong> {{ num_books }}</li>-->
<!--    <li><strong>Egzempliorių:</strong> {{ num_instances }}</li>-->
<!--    <li><strong>Laisvų egzempliorių:</strong> {{ num_instances_available }}</li>-->
<!--    <li><strong>Autorių:</strong> {{ num_authors }}</li>-->
<!--  </ul>-->
<!--  <p>Čia jūs lankotes {{ num_visits }}-ą kartą.</p>-->

mysite/library/templates/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>
  </br>
  {% if books %}
  <ul>
    {% for book in books %}
      <li>
        <a href="{% url 'book' book.id %}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}

  {% endblock %}

mysite/library/templates/user_book.html
{% extends "base.html" %}

{% block title %}User book instance{% endblock %}

{% block content %}
    <h1>Mano paimta knyga:</h1>
    <hr>
        <ul>
        <img class="rounded-circle" style="max-width:80%;" src="{{book.book.cover.url}}">
        <li><strong class="{% if book.is_overdue %}text-danger{% endif %}">Pavadinimas: {{book.book.title}}</strong></li>
        <li><strong>Gražinimo terminas:</strong> {{book.due_back}}</li>
        <li><strong>Statusas:</strong> {{book.get_status_display}}</li>
        {% if book.reader == user %}
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'user_book_update' book.id %}">Redaguoti</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'user_book_delete' book.id %}">Ištrinti</a>
        </div>
        {% endif %}
        <br/>
      </li>
    </ul>
{% endblock %}